### ISSUE TITLE
Add more keywords to package.json

### ISSUE THREAD

**Issue by chenghw** [giantmachines/redux-websocket#118]
Currently on npmjs, `@giantmachines/redux-websocket` only have a single keyword which is `redux`. I think we should add least these: `websocket`, `typescript` and maybe `middleware`

Thoughts on any others?

**Comment by mechmillan** [comment]
Maybe 'javascript' and 'actions' or 'flux-standard-actions' ?

**Comment by kevinmaes** [comment]
I think `middleware` for sure. Maybe also something like `real-time` and/or `streaming`.
