### ISSUE TITLE
Adding a changelog

### ISSUE THREAD

**Issue by orangecoding** [giantmachines/redux-websocket#140]
Hi,

thanks for building this lib. I'm using it with rematch. It would be helpful to provide a changelog. Most of the opensource dev's simply have a CHANGELOG.md within their repo.

Thanks and keep rockin!

**Comment by chenghw** [comment]
Hi! Thanks for commenting. Great point, we'll start doing this moving forward.

Thanks!

**Comment by chenghw** [comment]
Added in [1.3.0](https://github.com/giantmachines/redux-websocket/pull/153)
