### ISSUE TITLE
Usage with Next.js error

### ISSUE THREAD

**Issue by tifa2UP** [giantmachines/redux-websocket#146]
Hi 👋,

I'm trying to use the repo with next.js and render the code on the server, but I'm getting an error when instantiating the middleware stating that `window` is not defined. 

![image](https://user-images.githubusercontent.com/11590314/89712554-f14c0d80-d991-11ea-870b-bf286e8ffd64.png)

This is because the output file uses a window object: 
![image](https://user-images.githubusercontent.com/11590314/89712588-2a847d80-d992-11ea-9291-9daf3a215aac.png)

### Proposed solution:

Return `null` when the window object is not defined, aka the server render.

**Comment by tifa2UP** [comment]
After a day of digging, this change fixed it for me: 

![image](https://user-images.githubusercontent.com/11590314/89717109-84496f80-d9b3-11ea-80bb-7fd7711fbae7.png)

The window object is not available on SSR applications. 

Source: https://github.com/webpack/webpack/issues/6642

**Comment by tifa2UP** [comment]
Created a PR for the fix here #147

**Comment by chenghw** [comment]
@tifa2UP I've merged your fix in and bumped the version to 1.2.3. Thanks again.
