### ISSUE TITLE
Details or Guidance on Reconnecting

### ISSUE THREAD

**Issue by iMerica** [giantmachines/redux-websocket#15]
Upon redeploying, servers get rebooted and connections are closed server side. 

How can we gracefully handle reconnecting using this tool?

**Comment by brianmcallister** [comment]
Hey @iMerica! There's some logic in a PR for reconnection here: https://github.com/giantmachines/redux-websocket/pull/8

However, we're working on overhauling this library, and we're going to incorporate reconnection logic into our `1.0` release. In the meantime, check out that PR. There's also a fork published to npm that has simple reconnection logic built in.

I'm going to close this issue, but please reach out if you have any other questions while using this library.
