### ISSUE TITLE
No option to set Cookie with header in web socket

### ISSUE THREAD

**Issue by hussainahmad** [giantmachines/redux-websocket#150]
Hi, thanks for this library.  I want to connect Cookie in header with with websocket like protocol. I checked the library I didn't find any option to set cookie.

**Comment by chenghw** [comment]
Hi @hussainahmad , thanks for the issue.

I was researching on ways to send cookies with the Websocket, I can't find a solution. Based on the TypeScript types of a WebSocket interface as well as this [stackoverflow post](https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/41521871#41521871), I don't see this as a possibility.

If you have any thoughts on how this would be implemented. I'm open to suggestions or a PR.

**Comment by chenghw** [comment]
I am closing this issue for now, please re-open if need be.

**Comment by hussainahmad** [comment]
@chenghw  I want to set cookie in header like this. 
```
socket: new WebSocket(url, '', {
                headers: {
                    Cookie: sessionId
                }
            })
```
as in my scenario I establish socket connection in base of session ID .  I didn't get any clue for this. Thanks for the help.

**Comment by hussainahmad** [comment]
In my app I am setting cookie this way which is working fine.  I need an authorisation for user to establish sock connection.

**Comment by chenghw** [comment]
Hi @hussainahmad sorry for the late reply, I am not seeing this as a supported feature for HTML5 WebSockets.

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
https://www.tutorialspoint.com/html5/html5_websocket.htm

As well as the TS documentation for WebSocket, the constructor only takes 2 arguments like the two resources state above.

**Comment by hussainahmad** [comment]
@chenghw Thanks for your time. As this is based on TypeScript we can't do this. so I wrote my own middleware. closing this now .
