### ISSUE TITLE
Add a new `deserializer` option for message deserializing

### ISSUE THREAD

**Issue by elboletaire** [giantmachines/redux-websocket#154]
I'm sure I'm not the only one who always responds using json when using websockets. Having a `deserializer` option would make sense for these cases where our response is not intended to be a plain string, and to avoid using `JSON.parse` many times in different reducers.

**Comment by procchio6** [comment]
Hi @elboletaire, we will consider adding this feature in a future update. We think this can be added in a backwards compatible way following the same pattern as the serializer option. Thanks for the suggestion!

**Comment by elboletaire** [comment]
Yeah it can easily be backwards compatible (by default have nothing, so it's not deserialized), and I didn't say it but having it as a configurable callback allows not only to deserialize as json, but as any other desired format (like XML, or whatever people use in websockets).

**Comment by chenghw** [comment]
@elboletaire we've merged the feature https://github.com/giantmachines/redux-websocket/pull/157 and included it in `1.4.0`

Thanks
