### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by sebinator** [giantmachines/redux-websocket#33]
Hi, i wish to know what I'm doing wrong,
here i my dispatch

`
import { WEBSOCKET_CONNECT, WEBSOCKET_DISCONNECT } from '@giantmachines/redux-websocket';
...

const mapDispatchToProps = (dispatch) => {
    return {
        wssconnect: (url) => dispatch({type: WEBSOCKET_CONNECT,  payload: { url }}),
        wssdisconnect: () => dispatch({type: WEBSOCKET_DISCONNECT})
    }
}
`

and then to connect/disconnect:

`
this.props.wssconnect(url);
this.props.wssdisconnect();
`
but when i am trying to disconnect i get : 
"Closing WebSocket connection to undefined ..."

**Comment by brianmcallister** [comment]
Hey @sebinator, it looks like you're dispatching the action with the correct structure, but I don't see `url` defined anywhere in your code snippet. Is it defined in a higher scope?

**Comment by brianmcallister** [comment]
Going to close this out due to inactivity, but @sebinator if you're still having trouble feel free to reopen.
