### ISSUE TITLE
[Feature request] Callbacks for incoming messages

### ISSUE THREAD

**Issue by Sergeytroinin** [giantmachines/redux-websocket#56]
Sometimes it's really helpful to pass a callback, which will be fired when some response will come directly for a particular message. E.g:
```
// Outcoming message
{
  type: "UPDATE",
  payload: {},
  uuid: "some uuid"
}

// Incoming message
{
  type: "UPDATE_SUCCESFUL",
  payload: {},
  originalUUID: "some uuid"
}
```
Then we could match two messges and call some function, when corresponding message comes to the client. 
Are you considering adding such functionality? I could help with it if needed. I made similar systems in the past.

**Comment by Sergeytroinin** [comment]
Hey @brianmcallister 
I think it would be more clear if I provide an example from `redux-api-middleware`.
With that library, you could pass three action types, that will be fired in three cases
- Request started
- Request was successful
- Request failed

With WebSocket, it could be an optional param for `send` action. Like
```
dispatch(send({"message": "PING"}, {callbackAction: "PONG_ACTION"}))
```
With this option middleware will add some kind of `UUID` to the message and backend will be able to reply with the same `UUID`. If middleware will receive the message with existed `UUID`, it should dispatch corresponded action.

And yes, unique ID could be a totally separate feature. I made some kind of it as an internal library for one of the project and it would be great to have a public version in the open source, so I decided not do it from scratch, but add as a feature to the existed library. 

Actually, I could prepare a PR with basic functionality at some point, maybe it will be more clear with real code. 

Let me know if you have further questions.

**Comment by brianmcallister** [comment]
What about a solution along these lines; First, add an option to the middleware creator. This option would be a function that would return a JavaScript object, which would then be merged with the payload of the `WEBSOCKET_SEND` action:

```javascript
import reduxWebsocket from '@giantmachines/redux-websocket';

const reduxWebsocketMiddleware = reduxWebsocket({
    sendPayloadMixin: (_payload: any, _prefix: string) => ({
        myCustomKey: 'some-custom-value',
        uuid: myUuidCreator(),
    }),
});
```

...then, the `send` action creator would call that function:

```javascript
import { send } from '@giantmachines/redux-websocket';

send({ my: 'message' });

// ...would return:
{
    type: 'REDUX_WEBSOCKET::WEBSOCKET_SEND', 
    meta: {
        timestamp: 'some date',
    },
    payload: {
        my: 'message',
        // These keys got merged into the payload, because 
        // these were the return value of the `sendPayloadMixin` option.
        myCustomKey: 'some-custom-value',
        uuid: 'abcd-1234',
    },
}
```

That way, if you wanted a `uuid`, you could add it. You could name the key whatever you wanted, and you also include _whatever_ kind of tracking information your backend needed. From there, the middleware would dispatch a `REDUX_WEBSOCKET::MESSAGE` action like normal, and your backend could return whatever fields you needed to match up messages.

What do you think?

**Comment by brianmcallister** [comment]
Hey @Sergeytroinin, I'm going to close this because it's been a while, but feel free to reopen if this is still an issue for you.
