### ISSUE TITLE
Remove action type prefix in favor of a key in 'meta'.

### ISSUE THREAD

**Issue by brianmcallister** [giantmachines/redux-websocket#60]
I propose that we remove the ability to prefix our action types in favor of adding a key in the `meta` object of an action in order to identify which instance of the middleware an action is originating from.

The reason for proposing this is so that we can better type our actions with TypeScript. The prefixing is creating an issue where we can't effectively type our actions, because the `type` field can potentially be _anything_, due to concatenating whatever the user passes as a `prefix` with our base action types.

For instance, our `buildAction` helper function can't take `type` as `ActionType`, because we _have no idea what `type` is going to be_. Right now, our action is typed as (simplified):

```typescript
interface Action {
  type: string
  meta?: any
  payload?: any
}
```

...when it should actually be:

```typescript
type ActionType = 'CONNECT' | 'SEND'; // etc.

interface Action {
  type: ActionType
  meta?: {
    id: string
  }
  payload?: any
}
```

...where `action.meta.id`  could come from the `options` passed to `createMiddleware`.

**Comment by brianmcallister** [comment]
And I guess it's worth saying that this will be a breaking change and necessitate a 2.0 release. Wish I had thought of this sooner. 😓

**Comment by kevinmaes** [comment]
We are now working on a method that should provide type safety of the action type for TypeScript users while still retaining the simplicity of prepending the prefix for regular JS users. This will be part of a v2.
