### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by Nolence** [giantmachines/redux-websocket#61]
So I'm really new to TypeScript so I might not be understanding something but I'm not able to get the types for this package. The advice from from my IDE was

```
Could not find a declaration file for module '@giantmachines/redux-websocket'.
'c:/Users/rexma/Documents/vector_editor/front_end/node_modules/@giantmachines/redux-websocket/dist/bundle.js' implicitly has an 'any' type.
Try `npm install @types/giantmachines__redux-websocket` if it exists or add a new declaration (.d.ts) file containing `declare module '@giantmachines/redux-websocket';`
```

But trying to install `@types/giantmachines__redux-websocket` doesn't find anything. I noticed there is a types file in the `src` directory so I'm thinking I might just copy that into a declaration file but I'm hoping there is a better way

Any advice?

**Comment by brianmcallister** [comment]
I made some changes in the #62 PR. Could you try pulling the repo down and using `npm link` to test locally? I made changes in the demo app and it's working great, but I'd like to make sure it's working for you as well before I publish a new version.

**Comment by Nolence** [comment]
Nice! I got it working on my end too

**Comment by brianmcallister** [comment]
OK great, thanks so much for testing. I'll get a new minor version out once that PR gets merged.

**Comment by brianmcallister** [comment]
Just published. I'll go ahead and close this for the time being. Feel free to open up any other issues.

**Comment by Nolence** [comment]
I'm sorry @brianmcallister, but that did not fix it I don't think.

While testing it I did get it locally linked and it did work but now comparing the sym linked `redux-websocket` and the distributed one, I think something is getting lost in translation but I don't know what's causing the difference.

Here is the distributed 1.1.1:

![distributed-redux-websocket](https://user-images.githubusercontent.com/29642168/56962295-70a62c80-6b13-11e9-8399-78085110f7c1.PNG)

and here is the sym linked one:

![built-redux-websocket](https://user-images.githubusercontent.com/29642168/56962320-7d2a8500-6b13-11e9-8b53-3fd601ebdbb8.PNG)

Like I said, I got full type support from the locally built one but not the one I yarn installed (1.1.1). For the sym linked one if I alt+click (opens file location) on the `redux-websocket` module path in one of my files, I'll get taken to `index.d.ts` but doing the same for the distributed just brings up the old warning:

![no-declaration-file](https://user-images.githubusercontent.com/29642168/56964021-903f5400-6b17-11e9-8bba-8de2e5bc9653.PNG)

Have no experience in this area so I'll leave it there.

Also thought I'd mention some problems I ran into while testing this in case anyone else wants to test. I ran into yarn/npm inconsistencies and in the end just stuck with npm. Don't name the PR branch folder 
you intend to sym-link `redux-websocket`. This installs an older package that is no longer maintained when you run `npm link redux-websocket`.

![redux-websocket-old](https://user-images.githubusercontent.com/29642168/56962144-0db49580-6b13-11e9-9989-b67108405bb6.PNG)

**Comment by brianmcallister** [comment]
@Nolence Thanks for the detail, I'll take a look. This is our first TypeScript library, so we're figuring it out as well!

**Comment by brianmcallister** [comment]
@Nolence Alright, give `1.1.2` a shot.

**Comment by Nolence** [comment]
You're awesome @brianmcallister. That did the trick!

Feel free to close again

**Comment by brianmcallister** [comment]
👍
