### ISSUE TITLE
handleBrokenConnection public

### ISSUE THREAD

**Issue by jingoldby** [giantmachines/redux-websocket#74]
Hi there,

first off thanks for making this package! 

I was wondering if there was any consideration given to making the handleBrokenConnection function public? In my case, I have a service deployed on a pod that dies gracefully, triggering the REDUX_WEBSOCKET::CLOSED action, but it does not trigger reconnect logic.

I would ideally like to just call handleBrokenConnection from redux middleware anytime the websocket connection is closed on my page.

I'll post on SO as well (might be more appropriate there) but just wanted to say thanks and see if you had any thoughts! 

Cheers.

**Comment by brianmcallister** [comment]
Hey @jingoldby! Thanks for submitting this.

I did consider making all of the methods on `ReduxWebSocket` public, but thinking about your use case, maybe it would be possible to do what the demo app does to simulate a disconnect?

Here's the code that does that: https://github.com/giantmachines/redux-websocket/blob/master/demo/src/app/components/Controls/Controls.tsx#L107-L113

It creates a new error event, and then dispatches it to the socket instance.

This will trigger `handleError`, which will dispatch an error action, and then provided you haven't called `disconnect`, will call `handleBrokenConnection`.

I would say give that a shot, and if that doesn't work, we can try another option.

**Comment by jingoldby** [comment]
@brianmcallister thanks for pointing me in the right direction! That worked 👍

**Comment by jingoldby** [comment]
@brianmcallister hi again,

sorry to disturb again but I've noticed that upon reconnection the handleBrokenConnection setInterval function seems to continue firing even after a successful reconnect resulting in heaps of websocket network requests.

Might need a clearInterval on this.reconnectionInterval?

**Comment by brianmcallister** [comment]
No problem, thanks for trying out this library!

Question for you... do you see the open action getting dispatched when the library reconnects? The handler for the open event should clear the interval.

**Comment by jingoldby** [comment]
hi @brianmcallister,

I do see the open action... oddly enough, I actually see a 'closed' action fire after I receive 'reconnected', which then triggers my manual error call in my middleware (same as the demo window.dispatchEvent(new Error('error')) ) and causes the infinite loop of reconnection attempts.

not sure if you know why this extra closed call happens or how in my middleware I can get around this.... 

Cheers mate!

**Comment by brianmcallister** [comment]
Huh, that error is pretty strange. Do you have the Redux dev tools set up in your application? Can you inspect the payloads of the actions that are getting dispatched?

**Comment by jingoldby** [comment]
hey @brianmcallister!

so I looked into it further and you can actually see what's happening with my app if you click the "Simulate Disconnect" button in your demo a few times quickly (it kicks it into an infinite loop of attempted reconnects).

I forked your repo and just added a couple of lines to make sure handleBrokenConnection isn't kicked off multiple times before a reconnection happens ([see here](https://github.com/jingoldby/redux-websocket/commit/dd5ebf98c4ab83bc6b3b74ded81c7504121dbfdb)).

**Comment by brianmcallister** [comment]
Got it, thanks for that. I'll reopen this now, take a look at your changes, and see if I can get this fixed up.

**Comment by ubeid** [comment]
was just looking at this issue today. I also had a look at jingoldby's solution. 

The loop occurs because in the "handleError" function you're calling "handleBrokenConnection" again, resetting the interval function rather than letting the interval time elapse. Jingoldby tries to avoid this by setting the "alreadyConnected" flag. But this doesn't cater for the reconnectInterval time not being respected. Disclaimer: I didn't go through the logic properly. 

Maybe this will help with the fix. Cheers!

**Comment by brianmcallister** [comment]
Hey @ubeid thanks for taking a look. My plan is close to what you described, avoiding kicking off a reconnection process when one is already happening. I'll get a solution for that up as soon as I'm able.
