### ISSUE TITLE
Unconventional Redux Usage

### ISSUE THREAD

**Issue by iMerica** [giantmachines/redux-websocket#75]
Hi,

I'm finding the [Usage](https://github.com/giantmachines/redux-websocket#usage) steps to be a bit counter-intuitive.

To illustrate the problem, have a look at the official [Redux docs example app](https://redux.js.org/basics/example). You'll observe that actions are called within React components using `mapDispatchToProps`.  They are not called with `store.dispatch(myAction(...))` like the way you're describing in the README.

**Comment by brianmcallister** [comment]
You don't need to use Redux with `react-redux`. As long as you have access to the `dispatch` function, you can dispatch actions from anywhere.

Have a look at the [dispatching actions](https://redux.js.org/basics/store#dispatching-actions) section of the Redux documentation.

**Comment by iMerica** [comment]
Yep, I have that working already. 

It sounds like this tool is basically trying to stay agnostic about the UI then (it could work in React or something else). Okay, thats fine 👍.
