### ISSUE TITLE
Closed vs Broken Connection

### ISSUE THREAD

**Issue by danitt** [giantmachines/redux-websocket#85]
hi team, love your work here 👍

was hoping someone would be kind enough to shed some light on a connection persistence issue I'm stuck on

I've noticed that killing my ws server often only triggers a client-side 'closed' event without an error event, and this - understandably - does not trigger reconnection attempts

Scratching my head over how to neatly handle all connection drops (both closed and broken), to start the reconnect loop, to handle cases like this

cheeeeers

**Comment by brianmcallister** [comment]
Huh, interesting. I didn't take into account that the server could also close the connection.

I suppose it would be easy enough to build in an option for this, but if possible I'd love to hear a bit more about your use case. I would think that if the connection was closed server side, the connection is intended to be closed and therefore the server wouldn't expect a client to immediately connect again.

Is it possible for you to go into a bit more detail about what you're doing?

**Comment by danitt** [comment]
hi @brianmcallister thanks so much for getting back to me

we're building an internal web app that relies entirely on an active websocket connection, so if the connection dies for any reason, it needs to lock down and just wait until it can establish a conn again

if you have any thoughts on how this could be handled, would be much appreciated 💯

**Comment by brianmcallister** [comment]
OK, so one option could be to handle the close events with a custom middleware, and dispatch another connect action when you see a close event happen. That would be pretty easy to implement, but it wouldn't have the same handling as a broken connection (retrying over and over again until it succeeds).

It could look roughly something like this:

```js
const customMiddleware = store => next => action => {
    if (action.type === `REDUX_WEBSOCKET::CLOSE`) {
      store.dispatch(connect(url));
    }

    next(action);
};
```

**Comment by danitt** [comment]
@brianmcallister thanks mate, think I will aim for the gold standard and write a fork with a "reconnectOnClosed" option - will let you when complete, in case it's something you'd like in the repo 💫
