### ISSUE TITLE
Possible to send details to server for broken connections vs disconnected connections?

### ISSUE THREAD

**Issue by stdmn** [giantmachines/redux-websocket#88]
**Background:**

I'm using AWS Lambda to enable websocket-based communication between my database and the front end. The basic gist of how this works is that when the front-end connects to the backend via websocket, the backend creates a DynamoDB entry with the connection ID. This connection ID is then used to send messages back to the client across different runs of the Lambda functions. (see [https://serverless.com/blog/api-gateway-websockets-example/](https://serverless.com/blog/api-gateway-websockets-example/) for more info.

**Issue:**

When the connection times out and breaks, the typical "disconnect" event is sent to the Lambda function. 

<img width="998" alt="Screen Shot 2019-09-23 at 5 43 55 PM" src="https://user-images.githubusercontent.com/17128916/65465288-d8924200-de29-11e9-9553-267f88228e4c.png">

The problem is that my Lambda disconnect function deletes the DynamoDB entry that is used to allow for continuity across Lambda function calls. I'm not sure if this is a Websocket problem or is unique to this library, but I was hoping that this library could send some kind of info to let the backend know that the connection has been broken instead of disconnected manually so that I can let my server know not to delete the connection info.

Any idea if this is possible?

**Comment by brianmcallister** [comment]
Huh, this is an interesting problem. The issue with your proposed solution is that if the connection has already been broken or disconnected, there's no way to send anything back to the server (in fact, this library does _not_ send its own status messages back to your server, only messages you ask it to send).

I'm not familiar with API Gateway WebSockets... is there a way for you to manually handle connection events on that side? Or, I see `$connect` and `$disconnect` events in the sample configuration file on the page you linked to. Is there an `$error` event you can use?

Thinking about this at a higher level, if a connection timed out and broke, this library would automatically try and reconnect, which would create a new connection. If you had a new connection, you'd want a new connection ID, right? If that were successfully persisted in the database, would the framework still be able to route responses to the correct client, the same as if it were a "net new" connection?

**Comment by stdmn** [comment]
I decided to go a different, somewhat hack-y route. I think what I was encountering was a server timeout at around 2 mins, so I just used client-side `window.setInterval` to ping the server every 45 seconds. This seems to solve the main problem. I'll probably have to write in some reconnect logic to store some info in the client in case of a broken connection.

**Comment by brianmcallister** [comment]
OK, I'll go ahead and close this for now then. Feel free to re-open if you have any further questions.
