### ISSUE TITLE
Distinguish beween server http responses

### ISSUE THREAD

**Issue by lordi** [giantmachines/redux-websocket#95]
If a http error code is returned during connect, a PREFIX::ERROR message is dispatched, but the action object does not contain the http error code. Thus it is not possible to distinguish between 401 and timeout, for instance.

**Comment by kevinmaes** [comment]
Hi @lordi Thanks for filing this issue. Apologies for the delayed response but we are happy to look into this now.

**Comment by kevinmaes** [comment]
We will address this issue as part of #103 for an upcoming v2 release.
